/// <reference path="Scripts/jquery-2.2.0.js" />
/// <reference path="notify.js" />
//https://notifyjs.jpillora.com/

var CurrentPageIndex = 1;
var Global_JsonData;
var Global_HeaderFromJson = [];
var settings;
var table;
var HeaderNamesFromJson = [];
var dropdownListSelectedValues = [];
var TotalPages;
var colSpanForNoreCords;


var jsonData;


(function ($) {

    $.fn.jdgrid = function (options) {

        // Default options
        var settings = $.extend({
            header:[],
            dataSourceurl: '',
            editTemplateUrl: '',
            primaryKey: '',
            deleteUrl: '',
            deleteParamName:'',
            saveUrl: '',
            saveParamName:'',
        }, options);

        //1.Load table tags
       //First we call parital view which will have theader,tbody,tr,tfooter
        GetPartialView();

       



        //2.Edit and Delete buttons will be autogenerated with here
        //3.Edit 


        //Functions-------------------------------------
        function GetPartialView() {
            this.append(getView(settings.dataSourceurl, "GET",));
        }





        function getView(url, type, data) {
            //Set data value for ajax calls
            if (data != "") {
                $.ajaxSetup({
                    data: data
                });
            }

            $.ajax({
                type: type,
                url: url,
                async: false,
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    if (response.hasOwnProperty('d')) {
                        return response.d;
                    }
                    else if (Array.isArray(response)) {
                        return response;
                    }
                },
                error: function (xhr, x, p) {
                    console.log(xhr.responseText);
                    console.log(x.toString());
                }
            });
        }
        //
        function postData(url, type, data = "") {
            //Set data value for ajax calls
            if (data != "") {
                $.ajaxSetup({
                    data: data
                });
            }

            $.ajax({
                type: "POST",
                url: settings.surl,
                async: false,
                dataType: 'json',
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    if (response.IsSuccess) {
                        $.notify(response.Message, "success");
                    } else {
                        $.notify(response.Message, "error");
                    }
                    //$.notify("Do not press this button", "info");
                    //$.notify("Warning: Self-destruct in 3.. 2..", "warn");
                },
                error: function (xhr, x, p) {
                    //console.log('something went wrong, please try again');
                    $.notify('something went wrong, please try again', "error");
                }
            });
        }
        // Apply options
       // return this.append('Hello ' + settings.name + '!');
        //End Functions-----------------------------------

    };

}(jQuery));